services:

  endpoint:
    image: nginx:alpine
    ports:
      - 8042:8000
    volumes:
      - ./docker/prod/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/prod/:/usr/share/netrunner
    depends_on:
      - server
    links:
      - server

  server:
    image: acollign/netrunner
    volumes:
      - "./docker/prod/prod.edn:/opt/netrunner/prod.edn"
    depends_on:
      - database
    links:
      - database:mongo

  database:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./data/db-prod:/data/db
